package services

import (
	"context"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"net/url"
	"strings"
	"time"

	"github.com/authsec-ai/authsec/internal/spire/domain/repositories"
	"github.com/authsec-ai/authsec/internal/spire/infrastructure/database"
	"github.com/authsec-ai/authsec/internal/spire/infrastructure/vault"

	"github.com/sirupsen/logrus"
)

// WorkloadAttestationService handles workload attestation and SVID issuance
type WorkloadAttestationService struct {
	connManager          *database.ConnectionManager
	tenantRepo           repositories.TenantRepository
	workloadEntryService *WorkloadEntryService
	vaultClient          *vault.Client
	logger               *logrus.Entry
}

// NewWorkloadAttestationService creates a new workload attestation service
func NewWorkloadAttestationService(
	connManager *database.ConnectionManager,
	tenantRepo repositories.TenantRepository,
	workloadEntryService *WorkloadEntryService,
	vaultClient *vault.Client,
	logger *logrus.Entry,
) *WorkloadAttestationService {
	return &WorkloadAttestationService{
		connManager:          connManager,
		tenantRepo:           tenantRepo,
		workloadEntryService: workloadEntryService,
		vaultClient:          vaultClient,
		logger:               logger,
	}
}

// AttestWorkloadRequest represents a workload attestation request from an agent
type AttestWorkloadRequest struct {
	TenantID  string            `json:"tenant_id"`
	AgentID   string            `json:"agent_id"`   // Agent's SPIFFE ID
	Selectors map[string]string `json:"selectors"`  // Workload selectors collected by agent
	CSR       string            `json:"csr"`         // PEM-encoded CSR generated by the workload
}

// AttestWorkloadResponse represents the SVID issued to the workload
type AttestWorkloadResponse struct {
	SpiffeID    string    `json:"spiffe_id"`
	Certificate string    `json:"certificate"`  // X.509 certificate (PEM)
	TrustBundle string    `json:"trust_bundle"` // CA bundle (PEM)
	ExpiresAt   time.Time `json:"expires_at"`
	TTL         int       `json:"ttl"` // TTL in seconds
}

// AttestWorkload performs workload attestation and issues SVID
func (s *WorkloadAttestationService) AttestWorkload(ctx context.Context, req *AttestWorkloadRequest) (*AttestWorkloadResponse, error) {
	s.logger.WithFields(logrus.Fields{
		"tenant_id": req.TenantID,
		"agent_id":  req.AgentID,
		"selectors": req.Selectors,
	}).Info("Attesting workload")

	// Get tenant from master database to retrieve Vault mount configuration
	tenant, err := s.tenantRepo.GetByID(ctx, req.TenantID)
	if err != nil {
		s.logger.WithField("tenant_id", req.TenantID).WithError(err).Error("Failed to fetch tenant from master database")
		return nil, fmt.Errorf("failed to fetch tenant vault mount: %w", err)
	}

	if !tenant.IsActive() {
		s.logger.WithField("tenant_id", req.TenantID).Error("Tenant is not active")
		return nil, fmt.Errorf("tenant is not active")
	}

	// Use vault mount as-is (should be in format: pki/tenant.domain.com)
	tenantVaultMount := tenant.VaultMount
	if tenantVaultMount == "" {
		s.logger.WithField("tenant_id", req.TenantID).Error("Tenant vault mount is empty")
		return nil, fmt.Errorf("tenant vault mount is not configured")
	}

	// 1. Find matching workload entries based on selectors
	matchingEntries, err := s.workloadEntryService.FindMatchingEntries(ctx, req.TenantID, req.Selectors)
	if err != nil {
		s.logger.WithField("tenant_id", req.TenantID).WithError(err).Error("Failed to find matching workload entries")
		return nil, fmt.Errorf("failed to find matching workload entries: %w", err)
	}

	if len(matchingEntries) == 0 {
		s.logger.WithFields(logrus.Fields{
			"tenant_id": req.TenantID,
			"selectors": req.Selectors,
		}).Warn("No matching workload entries found")
		return nil, fmt.Errorf("no workload entry matches the provided selectors")
	}

	// 2. Select the best matching entry: prefer entries with the most selector matches.
	// Among ties, prefer entries that have a parent_id matching the requesting agent.
	var entry = matchingEntries[0]
	bestScore := 0
	for _, candidate := range matchingEntries {
		score := len(candidate.Selectors)
		// Boost score for exact parent match
		if candidate.ParentID == req.AgentID {
			score += 1000
		}
		if score > bestScore {
			bestScore = score
			entry = candidate
		}
	}

	s.logger.WithFields(logrus.Fields{
		"entry_id":   entry.ID,
		"spiffe_id":  entry.SpiffeID,
		"parent_id":  entry.ParentID,
		"candidates": len(matchingEntries),
	}).Info("Selected best matching workload entry")

	// 3. Verify agent is authorized to request this workload's SVID.
	// Per SPIRE spec: require exact parent_id match, or allow if parent_id is unassigned (empty).
	agentAuthorized := entry.ParentID == "" || entry.ParentID == req.AgentID
	if !agentAuthorized {
		s.logger.WithFields(logrus.Fields{
			"agent_id":        req.AgentID,
			"expected_parent": entry.ParentID,
		}).Warn("Agent not authorized for this workload")
		return nil, fmt.Errorf("agent %s is not authorized for workload %s (expected parent: %s)",
			req.AgentID, entry.SpiffeID, entry.ParentID)
	}

	// 4. Validate workload-submitted CSR (workload generates its own keypair per SPIRE spec)
	if req.CSR == "" {
		return nil, fmt.Errorf("CSR is required: workload must generate its own keypair and submit a CSR")
	}

	csrBlock, _ := pem.Decode([]byte(req.CSR))
	if csrBlock == nil {
		return nil, fmt.Errorf("invalid CSR format: failed to decode PEM block")
	}

	csr, err := x509.ParseCertificateRequest(csrBlock.Bytes)
	if err != nil {
		return nil, fmt.Errorf("failed to parse CSR: %w", err)
	}

	if err := csr.CheckSignature(); err != nil {
		return nil, fmt.Errorf("invalid CSR signature: %w", err)
	}

	// 5. Derive CommonName from SPIFFE ID for Vault compatibility
	spiffeURI, err := url.Parse(entry.SpiffeID)
	if err != nil {
		s.logger.WithFields(logrus.Fields{
			"spiffe_id": entry.SpiffeID,
		}).WithError(err).Error("Invalid SPIFFE ID format")
		return nil, fmt.Errorf("invalid SPIFFE ID format: %w", err)
	}
	pathParts := strings.Split(spiffeURI.Path, "/")
	cn := pathParts[len(pathParts)-1]

	csrPEM := []byte(req.CSR)

	// 6. Determine TTL
	var ttl int
	if entry.TTL != nil {
		ttl = *entry.TTL
	} else {
		ttl = 3600 // Default 1 hour
	}
	ttlStr := fmt.Sprintf("%ds", ttl)

	// 7. Issue certificate via Vault using workload role
	certReq := &vault.CertificateRequest{
		CSR:        string(csrPEM),
		CommonName: cn,
		TTL:        ttlStr,
		URISANs:    []string{entry.SpiffeID},
	}

	s.logger.WithFields(logrus.Fields{
		"pki_mount": tenantVaultMount,
		"spiffe_id": entry.SpiffeID,
		"ttl":       ttlStr,
	}).Info("Issuing workload certificate via Vault")

	certResp, err := s.vaultClient.IssueCertificate(ctx, tenantVaultMount, "workload", certReq)
	if err != nil {
		s.logger.WithField("spiffe_id", entry.SpiffeID).WithError(err).Error("Failed to issue certificate via Vault")
		return nil, fmt.Errorf("failed to issue certificate: %w", err)
	}

	// 8. Get CA bundle
	trustBundle, err := s.vaultClient.GetCABundle(ctx, tenantVaultMount)
	if err != nil {
		s.logger.WithError(err).Error("Failed to get CA bundle")
		return nil, fmt.Errorf("failed to get CA bundle: %w", err)
	}

	// 9. Store workload SVID record in database for audit/tracking
	if err := s.recordWorkloadSVID(ctx, req.TenantID, entry.ID, entry.SpiffeID, certResp.SerialNumber, ttl); err != nil {
		s.logger.WithField("spiffe_id", entry.SpiffeID).WithError(err).Warn("Failed to record workload SVID (continuing anyway)")
	}

	s.logger.WithFields(logrus.Fields{
		"spiffe_id":     entry.SpiffeID,
		"serial_number": certResp.SerialNumber,
		"ttl":           ttl,
	}).Info("Workload SVID issued successfully")

	return &AttestWorkloadResponse{
		SpiffeID:    entry.SpiffeID,
		Certificate: certResp.Certificate,
		TrustBundle: trustBundle,
		ExpiresAt:   time.Now().Add(time.Duration(ttl) * time.Second),
		TTL:         ttl,
	}, nil
}

// recordWorkloadSVID stores a record of issued workload SVID for audit/tracking
func (s *WorkloadAttestationService) recordWorkloadSVID(ctx context.Context, tenantID, entryID, spiffeID, serialNumber string, ttl int) error {
	// Get tenant-specific database connection
	tenantDB, err := s.connManager.GetTenantDB(ctx, tenantID)
	if err != nil {
		return fmt.Errorf("failed to connect to tenant database: %w", err)
	}

	// Insert workload SVID record for audit/tracking
	query := `
		INSERT INTO workload_svids (
			id, tenant_id, entry_id, spiffe_id, serial_number, ttl,
			issued_at, expires_at, created_at
		) VALUES (
			gen_random_uuid(), $1, $2, $3, $4, $5,
			NOW(), NOW() + ($5 || ' seconds')::interval, NOW()
		)
		ON CONFLICT DO NOTHING
	`

	_, err = tenantDB.ExecContext(ctx, query, tenantID, entryID, spiffeID, serialNumber, ttl)
	if err != nil {
		// Don't fail the attestation if we can't record it
		s.logger.WithField("spiffe_id", spiffeID).WithError(err).Warn("Failed to record workload SVID (non-critical)")
		return nil
	}

	return nil
}

// RevokeWorkloadSVID revokes a workload SVID by serial number
func (s *WorkloadAttestationService) RevokeWorkloadSVID(ctx context.Context, tenantID, serialNumber string) error {
	s.logger.WithFields(logrus.Fields{
		"tenant_id":     tenantID,
		"serial_number": serialNumber,
	}).Info("Revoking workload SVID")

	// Get tenant from master database to retrieve Vault mount configuration
	tenant, err := s.tenantRepo.GetByID(ctx, tenantID)
	if err != nil {
		s.logger.WithField("tenant_id", tenantID).WithError(err).Error("Failed to fetch tenant from master database")
		return fmt.Errorf("failed to fetch tenant vault mount: %w", err)
	}

	if !tenant.IsActive() {
		s.logger.WithField("tenant_id", tenantID).Error("Tenant is not active")
		return fmt.Errorf("tenant is not active")
	}

	// Use vault mount as-is (should be in format: pki/tenant.domain.com)
	tenantVaultMount := tenant.VaultMount

	if err := s.vaultClient.RevokeCertificate(ctx, tenantVaultMount, serialNumber); err != nil {
		s.logger.WithField("serial_number", serialNumber).WithError(err).Error("Failed to revoke certificate")
		return fmt.Errorf("failed to revoke certificate: %w", err)
	}

	s.logger.WithField("serial_number", serialNumber).Info("Workload SVID revoked successfully")

	return nil
}
